#!/usr/bin/env node
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { createInterface } from "node:readline";

const JOERN_VERSION = "4.0.523";
const JOERN_DIR = process.env.JOERN_CLI_PATH || join(homedir(), ".code-intel", "joern-cli");
const JOERN_INSTALL_DIR = join(homedir(), ".code-intel");

const GITHUB_RELEASE_URL = `https://github.com/joernio/joern/releases/download/v${JOERN_VERSION}/joern-install.sh`;

function log(msg: string) {
  console.log(`[code-intel-mcp] ${msg}`);
}

function error(msg: string) {
  console.error(`[code-intel-mcp] ERROR: ${msg}`);
}

function run(cmd: string, opts?: any) {
  return execSync(cmd, { stdio: "inherit", ...opts });
}

async function prompt(question: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function installJoern() {
  if (existsSync(join(JOERN_DIR, "joern"))) {
    log(`Joern already installed at ${JOERN_DIR}`);
    return;
  }

  log(`Installing Joern v${JOERN_VERSION}...`);
  mkdirSync(JOERN_INSTALL_DIR, { recursive: true });

  try {
    log("Downloading Joern install script...");
    run(`curl -L ${GITHUB_RELEASE_URL} -o /tmp/joern-install.sh`);
    run(`chmod +x /tmp/joern-install.sh`);
    run(`/tmp/joern-install.sh --install-dir ${JOERN_INSTALL_DIR} --version v${JOERN_VERSION}`);
    log(`Joern installed to ${JOERN_INSTALL_DIR}`);
  } catch {
    try {
      log("Install script failed. Trying manual download...");
      const zipUrl = `https://github.com/joernio/joern/releases/download/v${JOERN_VERSION}/joern-${JOERN_VERSION}.zip`;
      const zipPath = join(JOERN_INSTALL_DIR, `joern-${JOERN_VERSION}.zip`);
      run(`curl -L ${zipUrl} -o "${zipPath}"`);
      run(`cd "${JOERN_INSTALL_DIR}" && unzip -o "${zipPath}"`);
      run(`rm -f "${zipPath}"`);
      log(`Joern extracted to ${JOERN_INSTALL_DIR}`);
    } catch (e) {
      error(`Failed to install Joern: ${e}`);
      error("Please install Joern manually from https://github.com/joernio/joern/releases");
      process.exit(1);
    }
  }
}

async function startArangoDB(host: string, user: string, pass: string) {
  log("Starting ArangoDB via Docker...");
  try {
    run("docker compose -f docker-compose.yml up -d arangodb", { cwd: process.cwd() });
    log("Waiting for ArangoDB to be ready...");
    let ready = false;
    for (let i = 0; i < 30; i++) {
      try {
        run(`curl -s -o /dev/null -u "${user}:${pass}" ${host}/_api/version`, { stdio: "pipe" });
        ready = true;
        break;
      } catch {
        await new Promise((r) => setTimeout(r, 2000));
      }
    }
    if (ready) {
      log("ArangoDB is ready!");
    } else {
      error("ArangoDB did not become ready within 60 seconds");
      process.exit(1);
    }
  } catch {
    log("Docker not available. Please install Docker or start ArangoDB manually.");
    log("See https://www.arangodb.com/download/ for ArangoDB installation.");
  }
}

async function setupArangoDB() {
  log("Setting up ArangoDB collections and indexes...");
  try {
    run("bash setup-arangodb.sh", { cwd: process.cwd() });
  } catch {
    log("ArangoDB setup script failed. You may need to run it manually.");
  }
}

function writeEnvFile(config: Record<string, string>) {
  const envPath = join(process.cwd(), ".env");
  const lines = [
    "# code-intel-mcp environment configuration",
    "# Generated by: npx code-intel-mcp setup",
    "",
  ];
  for (const [key, value] of Object.entries(config)) {
    lines.push(`${key}=${value}`);
  }
  writeFileSync(envPath, lines.join("\n"), "utf-8");
  log(`Configuration written to ${envPath}`);
}

async function main() {
  console.log("");
  console.log("  ╔═══════════════════════════════════════════════════╗");
  console.log("  ║   code-intel-mcp Setup Wizard                    ║");
  console.log("  ║   Joern CPG + ArangoDB Code Intelligence         ║");
  console.log("  ╚═══════════════════════════════════════════════════╝");
  console.log("");

  const mode = process.argv[2] || "full";

  const arangoHost = process.env.ARANGO_HOST || "http://localhost:8529";
  const arangoUser = process.env.ARANGO_USER || "root";
  const arangoPass = process.env.ARANGO_PASS || "";
  const arangoDb = process.env.ARANGO_DB || "code_intel";

  if (mode === "joern" || mode === "full") {
    await installJoern();
  }

  if (mode === "arangodb" || mode === "full") {
    await startArangoDB(arangoHost, arangoUser, arangoPass);
    await setupArangoDB();
  }

  writeEnvFile({
    JOERN_CLI_PATH: JOERN_DIR,
    ARANGO_HOST: arangoHost,
    ARANGO_USER: arangoUser,
    ARANGO_PASS: arangoPass,
    ARANGO_DB: arangoDb,
  });

  console.log("");
  log("Setup complete! Add this to your MCP client config:");
  console.log("");
  console.log("  {");
  console.log('    "mcpServers": {');
  console.log('      "code-intel": {');
  console.log('        "command": "npx",');
  console.log('        "args": ["-y", "code-intel-mcp"],');
  console.log('        "env": {');
  console.log(`          "JOERN_CLI_PATH": "${JOERN_DIR}",`);
  console.log(`          "ARANGO_HOST": "${arangoHost}",`);
  console.log(`          "ARANGO_USER": "${arangoUser}",`);
  console.log(`          "ARANGO_PASS": "${arangoPass}",`);
  console.log(`          "ARANGO_DB": "${arangoDb}"`);
  console.log("        }");
  console.log("      }");
  console.log("    }");
  console.log("  }");
  console.log("");
}

main().catch((e) => {
  error(`Setup failed: ${e}`);
  process.exit(1);
});